# Generated by Django 3.2.13 on 2022-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='account',
            name='interests',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='интересы'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='пол'),
        ),
    ]
