# Generated by Django 3.2.13 on 2022-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_avatar',
            field=models.CharField(default='\\static\\images\x07ccount_icon.png', max_length=200),
        ),
    ]
