# Generated by Django 3.2.13 on 2022-06-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_avatar',
        ),
    ]
